### ISSUE TITLE
Kenapa harus pakai future dibagain controller delete bang?

### ISSUE THREAD

**Issue by irayshi** [kuldii/youtube_getx_getconnect#1]
kenapa tidak seperti ini aja dibagain controller deletenya bang?

void delete(String id) async {
    await Get.defaultDialog(
      title: "DELETE",
      middleText: "Apakah kamu yakin untuk menghapus data user ini?",
      textConfirm: "Ya",
      confirmTextColor: Colors.white,
      onConfirm: () {
        usersS().deleteUser(id).then((_) {
          users.removeWhere((element) => element.id == id);
        });
        Get.offAllNamed(RouteName.home);
      },
      textCancel: "Tidak",
    );
  }

**Comment by kuldii** [comment]
kalau mau ditungguin, buat dia jadi Future, kalau tidak ada yang ditunggu, bisa juga langsung void
